### ISSUE TITLE
Add gettext

### ISSUE THREAD

**Issue by zedtux** [linkyard/docker-kubectl#1]
Hey,

Your image looks really sexy but I'm missing the gettext package. Would you mind to add it please?

Thank you !

**Comment by msiegenthaler** [comment]
Hey, thanks
May I ask why you need this package? Because it'd like to keep the image as minimal as possible, but of course when there is a common use case I'm happy to add it.

**Comment by zedtux** [comment]
Yes sure, I'm using the `envsubst` command in order to replace variables in my YAML files and `gettext` is the package providing it.

**Comment by msiegenthaler** [comment]
Sounds good, I've added it to `master`/`latest`
